/* eslint-disable require-yield, eqeqeq */

import {
  Sprite,
  Trigger,
  Watcher,
  Costume,
  Color,
  Sound
} from "https://unpkg.com/leopard@^1/dist/index.esm.js";

export default class Sprite1 extends Sprite {
  constructor(...args) {
    super(...args);

    this.costumes = [
      new Costume("costume1", "./Sprite1/costumes/costume1.svg", {
        x: 48,
        y: 50
      }),
      new Costume("costume2", "./Sprite1/costumes/costume2.svg", {
        x: 46,
        y: 53
      })
    ];

    this.sounds = [
      new Sound("Meow", "./Sprite1/sounds/Meow.wav"),
      new Sound("Meow2", "./Sprite1/sounds/Meow2.wav"),
      new Sound("Meow3", "./Sprite1/sounds/Meow3.wav"),
      new Sound("Meow4", "./Sprite1/sounds/Meow4.wav"),
      new Sound("Meow5", "./Sprite1/sounds/Meow5.wav"),
      new Sound("Meow6", "./Sprite1/sounds/Meow6.wav"),
      new Sound("Meow7", "./Sprite1/sounds/Meow7.wav"),
      new Sound("Meow8", "./Sprite1/sounds/Meow8.wav"),
      new Sound("Meow9", "./Sprite1/sounds/Meow9.wav"),
      new Sound("Meow10", "./Sprite1/sounds/Meow10.wav"),
      new Sound("Meow11", "./Sprite1/sounds/Meow11.wav"),
      new Sound("Meow12", "./Sprite1/sounds/Meow12.wav"),
      new Sound("Meow13", "./Sprite1/sounds/Meow13.wav"),
      new Sound("Meow14", "./Sprite1/sounds/Meow14.wav"),
      new Sound("A Trumpet", "./Sprite1/sounds/A Trumpet.wav"),
      new Sound("A Trumpet2", "./Sprite1/sounds/A Trumpet2.wav"),
      new Sound("A Trumpet3", "./Sprite1/sounds/A Trumpet3.wav"),
      new Sound("A Trumpet4", "./Sprite1/sounds/A Trumpet4.wav"),
      new Sound("A Trumpet5", "./Sprite1/sounds/A Trumpet5.wav"),
      new Sound("A Trumpet6", "./Sprite1/sounds/A Trumpet6.wav"),
      new Sound("A Trumpet7", "./Sprite1/sounds/A Trumpet7.wav"),
      new Sound("A Trumpet8", "./Sprite1/sounds/A Trumpet8.wav"),
      new Sound("A Trumpet9", "./Sprite1/sounds/A Trumpet9.wav"),
      new Sound("A Trumpet10", "./Sprite1/sounds/A Trumpet10.wav"),
      new Sound("A Trumpet11", "./Sprite1/sounds/A Trumpet11.wav"),
      new Sound("A Trumpet12", "./Sprite1/sounds/A Trumpet12.wav"),
      new Sound("A Trumpet13", "./Sprite1/sounds/A Trumpet13.wav"),
      new Sound("A Trumpet14", "./Sprite1/sounds/A Trumpet14.wav"),
      new Sound("A Trumpet15", "./Sprite1/sounds/A Trumpet15.wav"),
      new Sound("A Trumpet16", "./Sprite1/sounds/A Trumpet16.wav"),
      new Sound("A Sax", "./Sprite1/sounds/A Sax.wav"),
      new Sound("A Sax2", "./Sprite1/sounds/A Sax2.wav"),
      new Sound("A Sax3", "./Sprite1/sounds/A Sax3.wav"),
      new Sound("A Sax4", "./Sprite1/sounds/A Sax4.wav"),
      new Sound("A Sax5", "./Sprite1/sounds/A Sax5.wav"),
      new Sound("A Sax6", "./Sprite1/sounds/A Sax6.wav"),
      new Sound("A Sax7", "./Sprite1/sounds/A Sax7.wav"),
      new Sound("A Sax8", "./Sprite1/sounds/A Sax8.wav"),
      new Sound("A Sax9", "./Sprite1/sounds/A Sax9.wav"),
      new Sound("A Sax10", "./Sprite1/sounds/A Sax10.wav"),
      new Sound("A Trombone", "./Sprite1/sounds/A Trombone.wav"),
      new Sound("A Trombone2", "./Sprite1/sounds/A Trombone2.wav"),
      new Sound("A Trombone3", "./Sprite1/sounds/A Trombone3.wav"),
      new Sound("A Trombone4", "./Sprite1/sounds/A Trombone4.wav"),
      new Sound("A Trombone5", "./Sprite1/sounds/A Trombone5.wav"),
      new Sound("A Trombone6", "./Sprite1/sounds/A Trombone6.wav"),
      new Sound("A Trombone7", "./Sprite1/sounds/A Trombone7.wav"),
      new Sound("A Trombone8", "./Sprite1/sounds/A Trombone8.wav"),
      new Sound("A Trombone9", "./Sprite1/sounds/A Trombone9.wav"),
      new Sound("A Trombone10", "./Sprite1/sounds/A Trombone10.wav"),
      new Sound("A Trombone11", "./Sprite1/sounds/A Trombone11.wav"),
      new Sound("A Trombone12", "./Sprite1/sounds/A Trombone12.wav"),
      new Sound("A Trombone13", "./Sprite1/sounds/A Trombone13.wav"),
      new Sound("A Trombone14", "./Sprite1/sounds/A Trombone14.wav"),
      new Sound("A Trombone15", "./Sprite1/sounds/A Trombone15.wav"),
      new Sound("A Trombone16", "./Sprite1/sounds/A Trombone16.wav"),
      new Sound("A Trombone17", "./Sprite1/sounds/A Trombone17.wav"),
      new Sound("A Trombone18", "./Sprite1/sounds/A Trombone18.wav"),
      new Sound("A Trombone19", "./Sprite1/sounds/A Trombone19.wav"),
      new Sound("A Trombone20", "./Sprite1/sounds/A Trombone20.wav"),
      new Sound("A Trombone21", "./Sprite1/sounds/A Trombone21.wav"),
      new Sound("A Trombone22", "./Sprite1/sounds/A Trombone22.wav"),
      new Sound("A Trombone23", "./Sprite1/sounds/A Trombone23.wav"),
      new Sound("A Trombone24", "./Sprite1/sounds/A Trombone24.wav"),
      new Sound("A Trombone25", "./Sprite1/sounds/A Trombone25.wav"),
      new Sound("A Trombone26", "./Sprite1/sounds/A Trombone26.wav"),
      new Sound("A Trombone27", "./Sprite1/sounds/A Trombone27.wav"),
      new Sound("A Trombone28", "./Sprite1/sounds/A Trombone28.wav"),
      new Sound("A Trombone29", "./Sprite1/sounds/A Trombone29.wav"),
      new Sound("A Trombone30", "./Sprite1/sounds/A Trombone30.wav"),
      new Sound("A Trombone31", "./Sprite1/sounds/A Trombone31.wav"),
      new Sound("A Trombone32", "./Sprite1/sounds/A Trombone32.wav"),
      new Sound("A Trombone33", "./Sprite1/sounds/A Trombone33.wav"),
      new Sound("A Trombone34", "./Sprite1/sounds/A Trombone34.wav"),
      new Sound("A Trombone35", "./Sprite1/sounds/A Trombone35.wav"),
      new Sound("A Trombone36", "./Sprite1/sounds/A Trombone36.wav"),
      new Sound("A Trombone37", "./Sprite1/sounds/A Trombone37.wav"),
      new Sound("A Trombone38", "./Sprite1/sounds/A Trombone38.wav"),
      new Sound("A Trombone39", "./Sprite1/sounds/A Trombone39.wav"),
      new Sound("A Trombone40", "./Sprite1/sounds/A Trombone40.wav"),
      new Sound("A Trombone41", "./Sprite1/sounds/A Trombone41.wav"),
      new Sound("A Trombone42", "./Sprite1/sounds/A Trombone42.wav"),
      new Sound("A Trombone43", "./Sprite1/sounds/A Trombone43.wav"),
      new Sound("A Trombone44", "./Sprite1/sounds/A Trombone44.wav"),
      new Sound("A Trombone45", "./Sprite1/sounds/A Trombone45.wav"),
      new Sound("A Trombone46", "./Sprite1/sounds/A Trombone46.wav"),
      new Sound("A Trombone47", "./Sprite1/sounds/A Trombone47.wav"),
      new Sound("A Trombone48", "./Sprite1/sounds/A Trombone48.wav"),
      new Sound("A Trombone49", "./Sprite1/sounds/A Trombone49.wav"),
      new Sound("A Trombone50", "./Sprite1/sounds/A Trombone50.wav"),
      new Sound("A Trombone51", "./Sprite1/sounds/A Trombone51.wav"),
      new Sound("A Trombone52", "./Sprite1/sounds/A Trombone52.wav"),
      new Sound("A Trombone53", "./Sprite1/sounds/A Trombone53.wav"),
      new Sound("A Trombone54", "./Sprite1/sounds/A Trombone54.wav"),
      new Sound("A Trombone55", "./Sprite1/sounds/A Trombone55.wav"),
      new Sound("A Trombone56", "./Sprite1/sounds/A Trombone56.wav"),
      new Sound("A Trombone57", "./Sprite1/sounds/A Trombone57.wav"),
      new Sound("A Trombone58", "./Sprite1/sounds/A Trombone58.wav"),
      new Sound("A Trombone59", "./Sprite1/sounds/A Trombone59.wav"),
      new Sound("A Trombone60", "./Sprite1/sounds/A Trombone60.wav"),
      new Sound("A Trombone61", "./Sprite1/sounds/A Trombone61.wav"),
      new Sound("A Trombone62", "./Sprite1/sounds/A Trombone62.wav"),
      new Sound("A Trombone63", "./Sprite1/sounds/A Trombone63.wav"),
      new Sound("A Trombone64", "./Sprite1/sounds/A Trombone64.wav"),
      new Sound("A Trombone65", "./Sprite1/sounds/A Trombone65.wav"),
      new Sound("A Trombone66", "./Sprite1/sounds/A Trombone66.wav"),
      new Sound("A Trombone67", "./Sprite1/sounds/A Trombone67.wav"),
      new Sound("A Trombone68", "./Sprite1/sounds/A Trombone68.wav"),
      new Sound("A Trombone69", "./Sprite1/sounds/A Trombone69.wav"),
      new Sound("A Trombone70", "./Sprite1/sounds/A Trombone70.wav"),
      new Sound("A Trombone71", "./Sprite1/sounds/A Trombone71.wav"),
      new Sound("A Trombone72", "./Sprite1/sounds/A Trombone72.wav"),
      new Sound("A Trombone73", "./Sprite1/sounds/A Trombone73.wav"),
      new Sound("A Trombone74", "./Sprite1/sounds/A Trombone74.wav"),
      new Sound("A Trombone75", "./Sprite1/sounds/A Trombone75.wav"),
      new Sound("A Trombone76", "./Sprite1/sounds/A Trombone76.wav"),
      new Sound("A Trombone77", "./Sprite1/sounds/A Trombone77.wav"),
      new Sound("A Trombone78", "./Sprite1/sounds/A Trombone78.wav"),
      new Sound("A Trombone79", "./Sprite1/sounds/A Trombone79.wav"),
      new Sound("A Trombone80", "./Sprite1/sounds/A Trombone80.wav"),
      new Sound("A Trombone81", "./Sprite1/sounds/A Trombone81.wav"),
      new Sound("A Trombone82", "./Sprite1/sounds/A Trombone82.wav"),
      new Sound("A Trombone83", "./Sprite1/sounds/A Trombone83.wav"),
      new Sound("A Trombone84", "./Sprite1/sounds/A Trombone84.wav"),
      new Sound("A Trombone85", "./Sprite1/sounds/A Trombone85.wav"),
      new Sound("A Trombone86", "./Sprite1/sounds/A Trombone86.wav"),
      new Sound("A Trombone87", "./Sprite1/sounds/A Trombone87.wav"),
      new Sound("A Trombone88", "./Sprite1/sounds/A Trombone88.wav"),
      new Sound("A Trombone89", "./Sprite1/sounds/A Trombone89.wav"),
      new Sound("A Trombone90", "./Sprite1/sounds/A Trombone90.wav"),
      new Sound("A Trombone91", "./Sprite1/sounds/A Trombone91.wav"),
      new Sound("A Trombone92", "./Sprite1/sounds/A Trombone92.wav"),
      new Sound("A Trombone93", "./Sprite1/sounds/A Trombone93.wav"),
      new Sound("A Trombone94", "./Sprite1/sounds/A Trombone94.wav"),
      new Sound("A Trombone95", "./Sprite1/sounds/A Trombone95.wav"),
      new Sound("A Trombone96", "./Sprite1/sounds/A Trombone96.wav"),
      new Sound("A Trombone97", "./Sprite1/sounds/A Trombone97.wav"),
      new Sound("A Trombone98", "./Sprite1/sounds/A Trombone98.wav"),
      new Sound("A Trombone99", "./Sprite1/sounds/A Trombone99.wav"),
      new Sound("A Trombone100", "./Sprite1/sounds/A Trombone100.wav"),
      new Sound("A Trombone101", "./Sprite1/sounds/A Trombone101.wav"),
      new Sound("A Trombone102", "./Sprite1/sounds/A Trombone102.wav"),
      new Sound("A Trombone103", "./Sprite1/sounds/A Trombone103.wav"),
      new Sound("A Trombone104", "./Sprite1/sounds/A Trombone104.wav"),
      new Sound("A Trombone105", "./Sprite1/sounds/A Trombone105.wav"),
      new Sound("A Trombone106", "./Sprite1/sounds/A Trombone106.wav"),
      new Sound("A Trombone107", "./Sprite1/sounds/A Trombone107.wav"),
      new Sound("A Trombone108", "./Sprite1/sounds/A Trombone108.wav"),
      new Sound("A Trombone109", "./Sprite1/sounds/A Trombone109.wav"),
      new Sound("A Trombone110", "./Sprite1/sounds/A Trombone110.wav"),
      new Sound("A Trombone111", "./Sprite1/sounds/A Trombone111.wav"),
      new Sound("A Trombone112", "./Sprite1/sounds/A Trombone112.wav"),
      new Sound("A Trombone113", "./Sprite1/sounds/A Trombone113.wav"),
      new Sound("A Trombone114", "./Sprite1/sounds/A Trombone114.wav"),
      new Sound("A Trombone115", "./Sprite1/sounds/A Trombone115.wav"),
      new Sound("A Trombone116", "./Sprite1/sounds/A Trombone116.wav"),
      new Sound("A Trombone117", "./Sprite1/sounds/A Trombone117.wav"),
      new Sound("A Trombone118", "./Sprite1/sounds/A Trombone118.wav"),
      new Sound("A Trombone119", "./Sprite1/sounds/A Trombone119.wav"),
      new Sound("A Trombone120", "./Sprite1/sounds/A Trombone120.wav"),
      new Sound("A Trombone121", "./Sprite1/sounds/A Trombone121.wav"),
      new Sound("A Trombone122", "./Sprite1/sounds/A Trombone122.wav"),
      new Sound("A Trombone123", "./Sprite1/sounds/A Trombone123.wav"),
      new Sound("A Trombone124", "./Sprite1/sounds/A Trombone124.wav"),
      new Sound("A Trombone125", "./Sprite1/sounds/A Trombone125.wav"),
      new Sound("A Trombone126", "./Sprite1/sounds/A Trombone126.wav"),
      new Sound("A Trombone127", "./Sprite1/sounds/A Trombone127.wav"),
      new Sound("A Trombone128", "./Sprite1/sounds/A Trombone128.wav"),
      new Sound("A Trombone129", "./Sprite1/sounds/A Trombone129.wav"),
      new Sound("A Trombone130", "./Sprite1/sounds/A Trombone130.wav"),
      new Sound("A Trombone131", "./Sprite1/sounds/A Trombone131.wav"),
      new Sound("A Trombone132", "./Sprite1/sounds/A Trombone132.wav"),
      new Sound("A Trombone133", "./Sprite1/sounds/A Trombone133.wav"),
      new Sound("A Trombone134", "./Sprite1/sounds/A Trombone134.wav"),
      new Sound("A Trombone135", "./Sprite1/sounds/A Trombone135.wav"),
      new Sound("A Trombone136", "./Sprite1/sounds/A Trombone136.wav"),
      new Sound("A Trombone137", "./Sprite1/sounds/A Trombone137.wav"),
      new Sound("A Trombone138", "./Sprite1/sounds/A Trombone138.wav"),
      new Sound("A Trombone139", "./Sprite1/sounds/A Trombone139.wav"),
      new Sound("A Trombone140", "./Sprite1/sounds/A Trombone140.wav"),
      new Sound("A Trombone141", "./Sprite1/sounds/A Trombone141.wav"),
      new Sound("A Trombone142", "./Sprite1/sounds/A Trombone142.wav"),
      new Sound("A Trombone143", "./Sprite1/sounds/A Trombone143.wav"),
      new Sound("A Trombone144", "./Sprite1/sounds/A Trombone144.wav"),
      new Sound("A Trombone145", "./Sprite1/sounds/A Trombone145.wav"),
      new Sound("A Trombone146", "./Sprite1/sounds/A Trombone146.wav"),
      new Sound("A Trombone147", "./Sprite1/sounds/A Trombone147.wav"),
      new Sound("A Trombone148", "./Sprite1/sounds/A Trombone148.wav"),
      new Sound("A Trombone149", "./Sprite1/sounds/A Trombone149.wav"),
      new Sound("A Trombone150", "./Sprite1/sounds/A Trombone150.wav"),
      new Sound("A Trombone151", "./Sprite1/sounds/A Trombone151.wav"),
      new Sound("A Trombone152", "./Sprite1/sounds/A Trombone152.wav"),
      new Sound("A Trombone153", "./Sprite1/sounds/A Trombone153.wav"),
      new Sound("A Trombone154", "./Sprite1/sounds/A Trombone154.wav"),
      new Sound("A Trombone155", "./Sprite1/sounds/A Trombone155.wav"),
      new Sound("A Trombone156", "./Sprite1/sounds/A Trombone156.wav"),
      new Sound("A Trombone157", "./Sprite1/sounds/A Trombone157.wav"),
      new Sound("A Trombone158", "./Sprite1/sounds/A Trombone158.wav"),
      new Sound("A Trombone159", "./Sprite1/sounds/A Trombone159.wav"),
      new Sound("A Trombone160", "./Sprite1/sounds/A Trombone160.wav")
    ];

    this.triggers = [
      new Trigger(Trigger.GREEN_FLAG, this.whenGreenFlagClicked)
    ];
  }

  *whenGreenFlagClicked() {
    this.stage.vars.myVariable = "Only 50 more until 250 sounds.";
  }
}
